Repository Omniscient-Job-Project/Omniscient-Front, pull requests merged in 2024-09, with the labels that each got.

#9 fix:reset css
  index.html
  src/assets/css/reset.css
Labels: Developing

#10 fix:core
  package-lock.json
  package.json
  src/components/curation/curationMain.vue
  src/components/index.vue
  vite.config.js
Labels: Developing

#11 feat:curation
  src/components/curation/curationMain.vue
  src/components/curation/curationSelect.vue
  src/views/curationView.vue
  src/views/indexView.vue
Labels: Developing

#12 feat:router
  src/App.vue
  src/assets/css/footer.css
  src/assets/css/header.css
  src/components/curation/curationSelect.vue
  src/components/footer/footer.vue
  src/components/header/header.vue
  src/components/index.vue
  src/router/index.js
  src/stores/rootstore.js
  src/views/curationView.vue
Labels: Developing

#13 fix:index
  src/components/index.vue
Labels: Developing

#14 feat certificate
  src/assets/css/header.css
  src/components/certificate/certificate.vue
  src/components/header/header.vue
  src/router/index.js
Labels: Developing

#17 feat:curationDetail #16
  src/assets/css/footer.css
  src/assets/css/header.css
  src/components/curation/curationDetail.vue
  src/components/header/header.vue
  src/views/curationView.vue
Labels: Developing

#19 feat:notice
  src/components/footer/footer.vue
  src/components/notice/noticeMain.vue
Labels: Developing

#20 fix mypage
  src/components/mypage/mypage.vue
Labels: Developing

#22 feat:login
  src/assets/img/googlelogin.png
  src/assets/img/kakaologin.png
  src/assets/img/naverlogin.png
  src/components/login/login.vue
  src/views/loginView.vue
Labels: Developing

#23 update css
  src/components/mypage/mypage.vue
Labels: Developing

#24 fix:notice
  src/components/notice/noticeMain.vue
Labels: Developing

#25 feat certificateSearch
  src/components/certificate/certificate.vue
  src/components/certificate/certificateSearch.vue
Labels: Developing

#26 fix:css
  src/components/curation/curationDetail.vue
  src/components/curation/curationMain.vue
  src/components/login/loginDetail.vue
  src/components/login/loginSection.vue
  src/views/loginView.vue
Labels: Developing

#27 fix profile
  src/components/mypage/mypage.vue
  src/components/mypage/profilePage.vue
Labels: Developing

#28 fix certificateSearch
  src/components/certificate/certificateSearch.vue
Labels: Developing

#30 fix certificate
  src/assets/css/footer.css
  src/assets/css/header.css
  src/components/certificate/certificate.vue
Labels: Developing

#31 fix:curation
  src/components/curation/curationMain.vue
  src/components/curation/curationSection.vue
  src/components/curation/curationSelect.vue
  src/components/header/header.vue
  src/views/curationView.vue
Labels: Developing

#32 update page
  src/components/mypage/mypage.vue
  src/components/mypage/profilePage.vue
Labels: Developing

#33 fix certificate & mypage
  package-lock.json
  src/assets/css/reset.css
  src/components/certificate/certificate.vue
  src/components/certificate/certificateSearch.vue
  src/components/mypage/mypage.vue
  src/components/mypage/profilePage.vue
  src/router/index.js
Labels: Developing

#34 fix:notice
  src/components/notice/noticeFAQ.vue
Labels: Developing

#35 fix Mypage
  src/components/mypage/mypage.vue
  src/components/mypage/profilePage.vue
  src/components/mypage/resumeEditPage.vue
  src/components/mypage/resumeManagementPage.vue
Labels: Developing

#36 update certificates-page
  src/components/mypage/certificatesPage.vue
  src/components/mypage/mypage.vue
  src/components/mypage/resumeManagementPage.vue
Labels: Developing

#37 feat : manager
  package-lock.json
  package.json
  src/App.vue
  src/assets/js/fetchTodayVisitorCount.js
  src/assets/js/fetchUserCount.js
  src/assets/js/fetchVisitorData.js
  src/assets/js/updateChart.js
  src/components/manager/adminMain.vue
  src/components/manager/faqList.vue
  src/components/manager/faqModify.vue
  src/components/manager/faqPost.vue
  src/components/manager/faqSection.vue
  src/components/manager/footer.vue
  src/components/manager/header.vue
  src/components/manager/managerMain.vue
  src/components/manager/noticeList.vue
  src/components/manager/noticeModify.vue
  src/components/manager/noticePost.vue
  src/components/manager/noticeSection.vue
  src/components/manager/sidebar.vue
  src/components/manager/userList.vue
  src/components/manager/userSection.vue
  src/main.js
  src/router/index.js
  src/stores/notice.js
  src/stores/resetVisitCount.js
  src/stores/rootstore.js
  src/stores/visitor.js
  src/views/managerFaq.vue
  src/views/managerMainV.vue
  src/views/managerNotice.vue
  src/views/managerUser.vue
Labels: Developing

#39 fix certificate & feat certificateSidebar
  src/assets/css/footer.css
  src/assets/css/header.css
  src/assets/css/reset.css
  src/assets/img/search-icon.svg
  src/components/certificate/certificate.vue
  src/components/certificate/certificateSidebar.vue
  src/components/footer/footer.vue
  src/components/header/header.vue
  src/router/index.js
Labels: Developing

#41 fix:router
  src/assets/css/header.css
  src/components/footer/footer.vue
  src/components/header/header.vue
  src/components/notice/noticeMain.vue
  src/router/index.js
  src/stores/rootstore.js
  src/views/noticeView.vue
Labels: Developing

#42 fix: add noticedetail
  src/components/notice/noticeDetail.vue
Labels: Developing

#43 update Mypage
  src/components/mypage/certificatesPage.vue
  src/components/mypage/mypage.vue
  src/components/mypage/resumeEditPage.vue
  src/components/mypage/resumeManagementPage.vue
Labels: Developing

#44 feat sidebar & update certificatesPage
  src/components/certificate/certificateSidebar.vue
  src/components/mypage/certificatesPage.vue
Labels: Developing

#45 update Mypage
  src/components/mypage/certificatesPage.vue
  src/components/mypage/mypage.vue
  src/components/mypage/scrapPage.vue
Labels: Developing

#46 fix:footer
  src/assets/css/footer.css
  src/components/footer/footer.vue
Labels: Developing

#47 fix mypage
  src/components/mypage/applicationsPageComponent.vue
  src/components/mypage/mypage.vue
Labels: Completion

#48 update certificateSidebar & fix certificate
  src/components/certificate/certificate.vue
  src/components/certificate/certificateSidebar.vue
Labels: Developing

#49 fix mypage
  src/components/mypage/mypage.vue
Labels: Developing

#50 fix certificate & fix certificateSidebar
  src/assets/img/arrow-down-icon.png
  src/assets/img/arrow-right-icon.png
  src/assets/img/bookmark-icon.svg
  src/assets/img/bookmark-yellow-icon.svg
  src/assets/img/image.png
  src/components/certificate/certificate.vue
  src/components/certificate/certificateSidebar.vue
Labels: Developing

#51 fix: login
  src/components/curation/curationMain.vue
  src/components/login/login.vue
  src/components/login/loginDetail.vue
  src/components/login/loginSection.vue
  src/router/index.js
Labels: Developing

#52 fix:noticedetail
  src/components/notice/noticeDetail.vue
  src/components/notice/noticeMain.vue
Labels: Developing

#54 fix : manager
  .env
  package-lock.json
  package.json
  src/assets/js/fetchTodayVisitorCount.js
  src/assets/js/fetchUserCount.js
  src/assets/js/fetchVisitorData.js
  src/assets/js/updateChart.js
  src/components/manager/adminMain.vue
  src/components/manager/faqList.vue
  src/components/manager/faqPost.vue
  src/components/manager/footer.vue
  src/components/manager/header.vue
  src/components/manager/managerMain.vue
  src/components/manager/noticeList.vue
  src/components/manager/noticeModify.vue
  src/components/manager/noticePost.vue
  src/components/manager/sidebar.vue
  src/components/manager/userList.vue
  src/router/index.js
  src/stores/counter.js
  src/stores/notice.js
  src/stores/resetVisitCount.js
  src/stores/visitor.js
  src/views/managerFaq.vue
  src/views/managerMainV.vue
  src/views/managerNotice.vue
  src/views/managerUser.vue
  src/views/noticeView.vue
  vite.config.js
Labels: Developing

#56 fix:curation
  src/components/curation/curationMain.vue
Labels: Developing

#57 fix:logindetail
  src/components/login/loginDetail.vue
Labels: Developing

#58 fix:curation carrer
  src/components/curation/curationMain.vue
Labels: Developing

#61 update crud
  src/components/mypage/profilePage.vue
Labels: Developing

#62 feat:curation pagenation
  src/components/curation/curationDetail.vue
  src/components/curation/curationMain.vue
Labels: Developing

#63 fix:login/signup
  src/components/login/login.vue
  src/components/login/loginDetail.vue
  src/components/login/loginSection.vue
  src/views/loginView.vue
Labels: Developing

#64 fix:login/signup
  src/components/login/signUp.vue
  src/views/signUp.vue
Labels: Developing

#65 update resume
  src/components/mypage/myhome.vue
  src/components/mypage/mypage.vue
  src/components/mypage/resumeEditPage.vue
  src/components/mypage/resumeManagementPage.vue
Labels: Developing

#66 update resumeManagementPage
  src/components/mypage/resumeManagementPage.vue
Labels: Developing

#68 fix : connecting manager with backend
  src/assets/js/fetchTodayVisitorCount.js
  src/components/manager/faqList.vue
  src/components/manager/faqModify.vue
  src/components/manager/faqPost.vue
  src/components/manager/managerMain.vue
  src/views/managerFaq.vue
  src/views/managerMainV.vue
  src/views/managerNotice.vue
  src/views/managerUser.vue
Labels: Developing

#71 update:curation
  src/components/curation/curationDetail.vue
  src/components/curation/curationMain.vue
Labels: Developing

#72 update:MyPage crud
  src/components/mypage/certificatesPage.vue
Labels: Developing

#73 feat:jobabaAPI
  src/components/curation/curationMain.vue
  src/components/curation/curationSection.vue
  src/components/curation/jobaba.vue
Labels: Developing

#74 fix css
  src/components/mypage/resumeManagementPage.vue
Labels: Developing

#75 feat:total job API
  src/components/curation/curationSection.vue
  src/components/curation/jobMain.vue
  src/router/index.js
Labels: Developing

#76 fix : 라우터, 엔드포인트
  src/assets/js/fetchTodayVisitorCount.js
  src/components/manager/adminMain.vue
  src/components/manager/faqList.vue
  src/components/manager/faqModify.vue
  src/components/manager/faqPost.vue
  src/components/manager/faqSection.vue
  src/components/manager/managerMain.vue
  src/components/manager/noticeList.vue
  src/components/manager/noticeModify.vue
  src/components/manager/noticePost.vue
  src/components/manager/noticeSection.vue
  src/components/manager/sidebar.vue
  src/components/manager/userList.vue
  src/components/manager/userSection.vue
  src/stores/counter.js
Labels: Developing

#77 update Storage
  src/components/curation/jobMain.vue
  src/components/curation/jobaba.vue
  src/components/mypage/scrapPage.vue
Labels: Developing

#79 fix:curation
  .env
  src/components/curation/curationMain.vue
  src/components/curation/curationSection.vue
  src/components/curation/detail.vue
Labels: Developing

#82 fix "board"
  src/components/board/boardList.vue
  src/components/board/postDetail.vue
  src/components/board/postForm.vue
  src/components/curation/jobMain.vue
  src/components/mypage/scrapPage.vue
Labels: Developing

#83 update scrap
  src/components/mypage/scrapPage.vue
Labels: Developing

#84 fix:signup
  src/components/login/signUp.vue
Labels: Developing

#85 update modal
  src/components/board/postDetail.vue
  src/components/board/postForm.vue
  src/components/mypage/certificatesPage.vue
  src/components/mypage/profilePage.vue
  src/components/mypage/resumeManagementPage.vue
Labels: Developing

#86 fix "comment"
  src/components/board/postDetail.vue
Labels: Developing

#87 update:index
  src/components/curation/jobMain.vue
  src/components/index.vue
Labels: Developing

#89 fix:index
  src/components/index.vue
Labels: Developing

#90 fix: modal
  src/components/board/postDetail.vue
Labels: Developing

#91 update: index css
  src/components/index.vue
Labels: Developing

#92 fix:notice,footer,router
  src/components/footer/footer.vue
  src/components/notice/noticeMain.vue
  src/router/index.js
Labels: Developing

#93 fix : 백앤드와 연동
  src/components/manager/faqList.vue
  src/components/manager/faqModify.vue
  src/components/manager/faqPost.vue
  src/components/manager/noticeList.vue
  src/components/manager/noticeModify.vue
  src/components/manager/noticePost.vue
  src/components/manager/sidebar.vue
  src/router/index.js
Labels: Developing

#94 fix : 백앤드와 연동
  src/components/manager/faqList.vue
  src/components/manager/faqModify.vue
  src/components/manager/noticeList.vue
  src/components/manager/noticeModify.vue
Labels: Developing

#95 fix "delete"
  src/components/board/board.vue
  src/components/board/postDetail.vue
  src/components/mypage/certificatesPage.vue
  src/components/mypage/profilePage.vue
  src/components/mypage/resumeManagementPage.vue
  src/router/index.js
Labels: Developing

#96 fix:curation
  src/components/curation/curationSection.vue
  src/components/curation/detail.vue
  src/components/curation/jobaba.vue
Labels: Developing

#97 "update css"
  src/components/curation/curationDetail.vue
  src/components/curation/detail.vue
  src/components/curation/jobaba.vue
Labels: Developing

#98 update: curation detail page
  src/components/curation/detail.vue
Labels: Developing

#101 feat:certificate Test Main page
  src/components/certificate/testMain.vue
Labels: Developing

#102 feat:job search
  src/components/curation/jobMain.vue
  src/components/index.vue
Labels: Developing

#103 fix:deatil css
  src/components/curation/detail.vue
Labels: Developing

#106 feat certificateView
  src/router/index.js
  src/views/certificateView.vue
Labels: Developing

#107 fix certificate
  src/components/certificate/certificate.vue
Labels: Developing

#108 feat : import Notice and FAQ from admin
  src/components/manager/noticeList.vue
  src/components/notice/noticeDetail.vue
  src/components/notice/noticeFAQ.vue
  src/components/notice/noticeMain.vue
  src/components/notice/noticeSection.vue
  src/components/notice/noticeSidebar.vue
  src/router/index.js
  src/views/noticeMainV.vue
  src/views/noticeView.vue
Labels: Developing

#109 "update css"
  src/components/board/postDetail.vue
  src/components/index.vue
  src/components/mypage/certificatesPage.vue
  src/components/mypage/mypage.vue
  src/components/mypage/profilePage.vue
  src/components/mypage/resumeEditPage.vue
  src/components/mypage/resumeManagementPage.vue
Labels: Developing

#110 "fix resume"
  src/components/mypage/resumeManagementPage.vue
Labels: Developing

#111 fix: login
  src/components/login/login.vue
Labels: Developing

#112 fix: 조회수 수정
  src/components/notice/noticeFAQ.vue
Labels: Developing

#113 update:job endpoint
  .env
  src/components/curation/detail.vue
  src/components/curation/jobMain.vue
Labels: Developing

#114 fix: 조회수 수정
  src/components/manager/noticeList.vue
  src/components/notice/noticeDetail.vue
  src/components/notice/noticeFAQ.vue
  src/components/notice/noticeMain.vue
Labels: Completion

#115 fix:curation endpoint
  src/components/curation/detail.vue
  src/components/curation/jobMain.vue
Labels: Developing

#116 fix certificate
  src/components/certificate/certificate.vue
Labels: Developing

#117 fix:env
  .env
Labels: Developing

#118 Comment crud
  src/components/board/postDetail.vue
Labels: Developing

#120 fix: 관리자 CSS 수정
  src/components/manager/managerMain.vue
  src/components/manager/sidebar.vue
  src/views/managerFaq.vue
  src/views/managerMainV.vue
  src/views/managerNotice.vue
  src/views/managerUser.vue
Labels: Completion

#121 feat:error page
  src/components/error/errorPage.vue
  src/router/index.js
  src/views/errorView.vue
Labels: Developing

#122 fix certificate
  src/components/certificate/certificate.vue
Labels: Developing

#123 fix certificate
  src/components/certificate/certificate.vue
Labels: Developing

#124 update css
  src/components/index.vue
Labels: Developing

#125 fix search & fitter
  src/components/certificate/certificate.vue
Labels: Developing

#126 feat termsView
  src/components/terms/terms.vue
  src/router/index.js
  src/views/termsView.vue
Labels: Developing

#127 feat header logo
  src/assets/img/logo/omniscientLogo.png
  src/components/header/header.vue
Labels: Developing

#128 feat:findAccount modal / fix:signup css
  src/components/login/findAccount.vue
  src/components/login/login.vue
  src/components/login/signUp.vue
Labels: Developing

#129 update: endpoint
  .env
  src/components/board/boardList.vue
  src/components/board/postDetail.vue
  src/components/board/postForm.vue
  src/components/certificate/certificate.vue
  src/components/certificate/testMain.vue
  src/components/curation/curationSection.vue
  src/components/curation/detail.vue
  src/components/curation/jobMain.vue
  src/components/login/login.vue
  src/components/login/signUp.vue
  src/components/manager/adminMain.vue
  src/components/manager/faqList.vue
  src/components/manager/faqModify.vue
  src/components/manager/faqPost.vue
  src/components/manager/managerMain.vue
  src/components/manager/noticeList.vue
  src/components/manager/noticeModify.vue
  src/components/manager/noticePost.vue
  src/components/manager/userList.vue
  src/components/mypage/certificatesPage.vue
  src/components/mypage/profilePage.vue
  src/components/mypage/resumeEditPage.vue
  src/components/mypage/resumeManagementPage.vue
  src/components/notice/noticeDetail.vue
  src/components/notice/noticeFAQ.vue
  src/components/notice/noticeMain.vue
Labels: Developing

#130 update: end point
  .env
  src/assets/img/logo/omniscientLogo.png
  src/components/board/boardList.vue
  src/components/board/postDetail.vue
  src/components/board/postForm.vue
  src/components/certificate/certificate.vue
  src/components/certificate/testMain.vue
  src/components/curation/detail.vue
  src/components/curation/jobMain.vue
  src/components/index.vue
  src/components/login/login.vue
  src/components/login/signUp.vue
  src/components/manager/adminMain.vue
  src/components/manager/faqList.vue
  src/components/manager/faqModify.vue
  src/components/manager/faqPost.vue
  src/components/manager/managerMain.vue
  src/components/manager/noticeList.vue
  src/components/manager/noticeModify.vue
  src/components/manager/noticePost.vue
  src/components/manager/userList.vue
  src/components/mypage/certificatesPage.vue
  src/components/mypage/profilePage.vue
  src/components/mypage/resumeEditPage.vue
  src/components/mypage/resumeManagementPage.vue
  src/components/notice/noticeDetail.vue
  src/components/notice/noticeFAQ.vue
  src/components/notice/noticeMain.vue
Labels: Developing

#131 fix certificate
  src/components/certificate/certificate.vue
Labels: Developing

#132 feat testjobs
  src/components/certificate/testJobs.vue
  src/views/testJobsView.vue
Labels: Developing

#133 Delete .env
  .env
Labels: Developing

#134 feat: curation index
  src/assets/img/logo/omniscientLogo.png
  src/components/curation/curationIndex.vue
  src/components/curation/jobMain.vue
Labels: Developing

#135 fix: error page
  src/components/error/errorPage.vue
Labels: Developing

#136 fix certificate & testjobs
  package-lock.json
  src/assets/img/certificate/image.png
  src/components/certificate/certificate.vue
  src/components/certificate/certificateSearch.vue
  src/components/certificate/testJobs.vue
  src/components/footer/footer.vue
  src/router/index.js
Labels: Developing

#137 fix terms link
  src/components/terms/terms.vue
Labels: Developing

#138 fix index 주석
  src/router/index.js
Labels: Developing

#139 update icon
  src/components/board/boardList.vue
  src/components/curation/curationIndex.vue
  src/components/index.vue
Labels: Developing

#140 "update css "
  src/components/curation/detail.vue
  src/components/index.vue
Labels: Developing

#141 deleted Search & sidebar & testMain
  src/components/certificate/certificateSearch.vue
  src/components/certificate/certificateSidebar.vue
  src/components/certificate/testMain.vue
Labels: Developing

#143 update modal
  src/components/header/header.vue
  src/components/index.vue
  src/components/login/login.vue
Labels: Developing

#144 fix scrap certificate
  src/components/certificate/certificate.vue
  src/components/mypage/scrapPage.vue
Labels: Developing

#145 fix 페이지 네이션
  src/components/certificate/testJobs.vue
Labels: Developing

#146 fix API_URL
  src/components/certificate/certificate.vue
  src/components/certificate/testJobs.vue
Labels: Developing

#147 feat image
  src/components/mypage/profilePage.vue
Labels: Developing

#148 fix: index.js
  src/router/index.js
Labels: Developing

#149 fix: index.js
  src/router/index.js
Labels: Developing

#150 feat womenJobs
  index.html
  public/favicon.ico
  src/components/certificate/certificate.vue
  src/components/curation/curationIndex.vue
  src/components/curation/jobMain.vue
  src/components/curation/womenJobs.vue
  src/components/index.vue
  src/router/index.js
Labels: Developing

#151 fix : 공지사항, FAQ
  src/assets/js/fetchTodayVisitorCount.js
  src/assets/js/fetchUserCount.js
  src/assets/js/fetchVisitorData.js
  src/assets/js/updateChart.js
  src/components/manager/adminMain.vue
  src/components/manager/faqList.vue
  src/components/manager/faqModify.vue
  src/components/manager/managerMain.vue
  src/components/manager/noticeList.vue
  src/components/manager/userList.vue
  src/stores/counter.js
  src/stores/notice.js
  src/stores/visitor.js
  src/views/managerNotice.vue
Labels: Completion

#152 update: curation
  src/components/curation/ElderlyJobs.vue
  src/components/curation/jobMain.vue
  src/components/curation/universityJob.vue
  src/main.js
  src/stores/rootstore.js
Labels: Developing

#153 feat category employment
  src/components/curation/employment.vue
  src/components/curation/jobMain.vue
Labels: Developing

#154 fix category
  src/components/curation/employment.vue
  src/components/curation/jobMain.vue
  src/components/curation/universityJob.vue
  src/components/curation/womenJobs.vue
Labels: Developing

#155 feat categorys bookmark & pagination
  src/components/curation/ElderlyJobs.vue
  src/components/curation/employment.vue
  src/components/curation/jobMain.vue
  src/components/curation/universityJob.vue
  src/components/curation/womenJobs.vue
Labels: Developing

#157 fix 주소 아이콘 색상 변경
  src/components/curation/jobMain.vue
Labels: Developing

#158 fix 검색창 위치 조정
  src/components/curation/ElderlyJobs.vue
  src/components/curation/employment.vue
  src/components/curation/jobMain.vue
  src/components/curation/universityJob.vue
  src/components/curation/womenJobs.vue
Labels: Developing

#159 update: myhome
  src/components/mypage/myhome.vue
Labels: Developing

#160 fix:find_password
  src/components/login/findAccount.vue
Labels: Developing

#161 fix:방문자수 불러오기
  src/assets/js/fetchTodayVisitorCount.js
  src/assets/js/fetchVisitorData.js
  src/assets/js/updateChart.js
  src/components/manager/faqList.vue
  src/components/manager/managerMain.vue
Labels: Completion

#162 fix: notice css
  src/components/notice/noticeFAQ.vue
  src/components/notice/noticeMain.vue
Labels: Developing

#163 fix : 앤드포인트맞추기
  src/assets/js/updateChart.js
  src/components/manager/adminMain.vue
  src/components/manager/faqList.vue
  src/components/manager/faqModify.vue
  src/components/manager/faqPost.vue
  src/router/index.js
  src/stores/visitor.js
Labels: Completion

#164 feat: admin_login
  src/components/footer/footer.vue
  src/components/login/login.vue
  src/stores/auth.js
Labels: Developing

#165 Update README.md
  README.md
Labels: Developing

#166 Update README.md
  README.md
Labels: Developing

#167 fix:faq 조회수
  src/components/notice/noticeFAQ.vue
Labels: Completion

#168 update readme
  README.md
Labels: Completion

#169 feat:회원탈퇴
  src/components/mypage/mypage.vue
  src/components/mypage/withdrawal.vue
  src/router/index.js
Labels: Developing

#171 fix:admin_login
  src/components/login/adminLogin.vue
  src/components/login/adminSignup.vue
  src/components/login/login.vue
  src/components/login/signUp.vue
  src/router/index.js
  src/views/adminLoginView.vue
  src/views/adminSignupView.vue
Labels: Developing

#172 fix scrapJobs
  src/components/curation/curationSection.vue
  src/components/curation/employment.vue
  src/components/curation/jobMain.vue
  src/components/mypage/scrapPage.vue
Labels: Developing

#173 fix jobMain
  src/components/curation/jobMain.vue
Labels: Developing

#174 fix: login
  src/components/login/login.vue
  src/stores/userAuth.js
Labels: Developing

#177 fix jobMain
  src/components/curation/jobMain.vue
Labels: Developing

#178 update: router, errorpage
  src/components/error/errorPage.vue
  src/router/index.js
Labels: Developing

#179 fix: router
  src/router/index.js
Labels: Developing

#180 fix: router
  src/router/index.js
Labels: Developing

#181 fix pagination css
  src/components/curation/jobMain.vue
Labels: Developing

#182 fix boardid & Code alignment
  src/components/board/boardList.vue
  src/components/board/postDetail.vue
  src/components/board/postForm.vue
Labels: Developing

#183 fix Sort code
  src/components/certificate/certificate.vue
  src/components/certificate/testJobs.vue
Labels: Developing

#184 fix component certificate
  src/components/certificate/certificate.vue
  src/components/certificate/gradeJobs.vue
  src/components/certificate/testJobs.vue
Labels: Developing

#185 "fix img"
  src/components/mypage/profilePage.vue
Labels: error, Developing

#186 fix component
  src/components/certificate/certificate.vue
  src/components/certificate/gradeJobs.vue
  src/components/certificate/testJobs.vue
Labels: Developing
